-- Eardle database initialization.
-- PostgreSQL runs this file automatically on first boot when the data volume is empty.
-- Creates all tables and seeds exercise data — no manual steps required.

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

-- Schema

CREATE TABLE "admin_users" (
    "id" serial PRIMARY KEY NOT NULL,
    "email" text NOT NULL,
    "password_hash" text NOT NULL,
    CONSTRAINT "admin_users_email_unique" UNIQUE("email")
);

CREATE TABLE "exercises" (
    "id" serial PRIMARY KEY NOT NULL,
    "category" text NOT NULL,
    "title" text NOT NULL,
    "prompt" text NOT NULL,
    "difficulty" text NOT NULL,
    "config" text NOT NULL,
    "choices" text NOT NULL,
    "answer" text NOT NULL,
    "created_at" integer NOT NULL,
    "updated_at" integer NOT NULL,
    "explanation" text
);

CREATE TABLE "users" (
    "id" serial PRIMARY KEY NOT NULL,
    "email" text,
    "password_hash" text,
    "google_id" text,
    "name" text,
    "nickname" text,
    "avatar_url" text,
    "created_at" integer NOT NULL,
    CONSTRAINT "users_email_unique" UNIQUE("email"),
    CONSTRAINT "users_google_id_unique" UNIQUE("google_id")
);

CREATE TABLE "feedback" (
    "id" serial PRIMARY KEY NOT NULL,
    "user_id" integer,
    "name" text,
    "email" text,
    "message" text NOT NULL,
    "created_at" integer NOT NULL
);

CREATE TABLE "sessions" (
    "id" serial PRIMARY KEY NOT NULL,
    "session_token" text NOT NULL,
    "exercise_id" integer NOT NULL,
    "user_id" integer,
    "answered" text NOT NULL,
    "correct" boolean NOT NULL,
    "created_at" integer NOT NULL
);

CREATE TABLE "daily_puzzles" (
    "id" serial PRIMARY KEY NOT NULL,
    "puzzle_date" text NOT NULL,
    "category" text NOT NULL,
    "difficulty" text NOT NULL,
    "exercise_id" integer NOT NULL,
    "exercise_snapshot" text NOT NULL,
    "performance_params" text NOT NULL,
    "source" text DEFAULT 'pool' NOT NULL,
    "created_at" integer NOT NULL,
    CONSTRAINT "daily_puzzles_puzzle_date_unique" UNIQUE("puzzle_date")
);

CREATE TABLE "daily_attempts" (
    "id" serial PRIMARY KEY NOT NULL,
    "puzzle_id" integer NOT NULL,
    "user_id" integer,
    "session_token" text NOT NULL,
    "category" text NOT NULL,
    "difficulty" text NOT NULL,
    "exercise_id" integer NOT NULL,
    "exercise_type" text,
    "topic" text,
    "guesses" text DEFAULT '[]' NOT NULL,
    "status" text DEFAULT 'in_progress' NOT NULL,
    "final_guess_count" integer,
    "finished_at" integer,
    "created_at" integer NOT NULL,
    "updated_at" integer NOT NULL
);

ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_exercise_id_exercises_id_fk" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "daily_puzzles" ADD CONSTRAINT "daily_puzzles_exercise_id_exercises_id_fk" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "daily_attempts" ADD CONSTRAINT "daily_attempts_puzzle_id_daily_puzzles_id_fk" FOREIGN KEY ("puzzle_id") REFERENCES "public"."daily_puzzles"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "daily_attempts" ADD CONSTRAINT "daily_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "daily_attempts" ADD CONSTRAINT "daily_attempts_exercise_id_exercises_id_fk" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON DELETE restrict ON UPDATE no action;
CREATE UNIQUE INDEX "daily_attempts_user_puzzle_uq" ON "daily_attempts" USING btree ("puzzle_id","user_id") WHERE "daily_attempts"."user_id" is not null;
CREATE UNIQUE INDEX "daily_attempts_token_puzzle_uq" ON "daily_attempts" USING btree ("puzzle_id","session_token") WHERE "daily_attempts"."user_id" is null;
CREATE INDEX "daily_attempts_puzzle_idx" ON "daily_attempts" USING btree ("puzzle_id");
CREATE INDEX "daily_attempts_category_idx" ON "daily_attempts" USING btree ("category","status");
CREATE INDEX "daily_attempts_exercise_type_idx" ON "daily_attempts" USING btree ("exercise_type","status");

-- Exercise seed data

INSERT INTO public.exercises VALUES (314, 'note', 'C — Natural', 'What note is this?', 'easy', '{"note":"C"}', '["C","D","E","F","G","A","B"]', 'C', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (315, 'note', 'D — Natural', 'What note is this?', 'easy', '{"note":"D"}', '["C","D","E","F","G","A","B"]', 'D', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (316, 'note', 'E — Natural', 'What note is this?', 'easy', '{"note":"E"}', '["C","D","E","F","G","A","B"]', 'E', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (317, 'note', 'F — Natural', 'What note is this?', 'easy', '{"note":"F"}', '["C","D","E","F","G","A","B"]', 'F', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (318, 'note', 'G — Natural', 'What note is this?', 'easy', '{"note":"G"}', '["C","D","E","F","G","A","B"]', 'G', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (319, 'note', 'A — Natural', 'What note is this?', 'easy', '{"note":"A"}', '["C","D","E","F","G","A","B"]', 'A', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (320, 'note', 'B — Natural', 'What note is this?', 'easy', '{"note":"B"}', '["C","D","E","F","G","A","B"]', 'B', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (321, 'note', 'C — 3 octaves', 'What note is this?', 'medium', '{"note":"C"}', '["C","D","E","F","G","A","B"]', 'C', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (322, 'note', 'D — 3 octaves', 'What note is this?', 'medium', '{"note":"D"}', '["C","D","E","F","G","A","B"]', 'D', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (323, 'note', 'E — 3 octaves', 'What note is this?', 'medium', '{"note":"E"}', '["C","D","E","F","G","A","B"]', 'E', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (324, 'note', 'F — 3 octaves', 'What note is this?', 'medium', '{"note":"F"}', '["C","D","E","F","G","A","B"]', 'F', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (325, 'note', 'G — 3 octaves', 'What note is this?', 'medium', '{"note":"G"}', '["C","D","E","F","G","A","B"]', 'G', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (326, 'note', 'A — 3 octaves', 'What note is this?', 'medium', '{"note":"A"}', '["C","D","E","F","G","A","B"]', 'A', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (327, 'note', 'B — 3 octaves', 'What note is this?', 'medium', '{"note":"B"}', '["C","D","E","F","G","A","B"]', 'B', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (328, 'note', 'C# / D♭', 'What note is this?', 'hard', '{"note":"C#"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'C#', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (329, 'note', 'D# / E♭', 'What note is this?', 'hard', '{"note":"D#"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'D#', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (330, 'note', 'F# / G♭', 'What note is this?', 'hard', '{"note":"F#"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'F#', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (331, 'note', 'G# / A♭', 'What note is this?', 'hard', '{"note":"G#"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'G#', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (332, 'note', 'A# / B♭', 'What note is this?', 'hard', '{"note":"A#"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'A#', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (333, 'note', 'C', 'What note is this?', 'hard', '{"note":"C"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'C', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (334, 'note', 'G', 'What note is this?', 'hard', '{"note":"G"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'G', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (504, 'note', 'D', 'What note is this?', 'hard', '{"note":"D"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'D', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (505, 'note', 'E', 'What note is this?', 'hard', '{"note":"E"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'E', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (506, 'note', 'F', 'What note is this?', 'hard', '{"note":"F"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'F', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (507, 'note', 'A', 'What note is this?', 'hard', '{"note":"A"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'A', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (508, 'note', 'B', 'What note is this?', 'hard', '{"note":"B"}', '["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]', 'B', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (574, 'chord', 'Major Chord', 'What type of chord is this?', 'easy', '{"type":"major"}', '["Major","Minor","Dominant 7th","Diminished"]', 'Major', 1783444284, 1783444284, 'A major chord is built from a root, major 3rd, and perfect 5th, giving it the bright, stable, ''happy'' sound that anchors most Western music. It''s the most common chord type and the natural resting point in a major key.');
INSERT INTO public.exercises VALUES (575, 'chord', 'Minor Chord', 'What type of chord is this?', 'easy', '{"type":"minor"}', '["Major","Minor","Dominant 7th","Diminished"]', 'Minor', 1783444284, 1783444284, 'A minor chord swaps the major 3rd for a minor 3rd, keeping the same root and perfect 5th. That single lowered note gives it a darker, more melancholic color, and it''s the natural resting point in a minor key.');
INSERT INTO public.exercises VALUES (576, 'chord', 'Dominant 7th', 'What type of chord is this?', 'easy', '{"type":"dom7"}', '["Major","Minor","Dominant 7th","Diminished"]', 'Dominant 7th', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (577, 'chord', 'Diminished Triad', 'What type of chord is this?', 'easy', '{"type":"dim"}', '["Major","Minor","Dominant 7th","Diminished"]', 'Diminished', 1783444284, 1783444284, 'A diminished chord stacks two minor 3rds on top of each other, giving every interval in the chord a tense, unstable quality. It has no strong ''home'' feeling of its own and almost always functions as a passing or transitional chord resolving somewhere else.');
INSERT INTO public.exercises VALUES (578, 'chord', 'Major Chord', 'What type of chord is this?', 'medium', '{"type":"major"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Major', 1783444284, 1783444284, 'A major chord is built from a root, major 3rd, and perfect 5th, giving it the bright, stable, ''happy'' sound that anchors most Western music. It''s the most common chord type and the natural resting point in a major key.');
INSERT INTO public.exercises VALUES (579, 'chord', 'Minor Chord', 'What type of chord is this?', 'medium', '{"type":"minor"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Minor', 1783444284, 1783444284, 'A minor chord swaps the major 3rd for a minor 3rd, keeping the same root and perfect 5th. That single lowered note gives it a darker, more melancholic color, and it''s the natural resting point in a minor key.');
INSERT INTO public.exercises VALUES (580, 'chord', 'Dominant 7th', 'What type of chord is this?', 'medium', '{"type":"dom7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Dominant 7th', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (581, 'chord', 'Diminished Triad', 'What type of chord is this?', 'medium', '{"type":"dim"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Diminished', 1783444284, 1783444284, 'A diminished chord stacks two minor 3rds on top of each other, giving every interval in the chord a tense, unstable quality. It has no strong ''home'' feeling of its own and almost always functions as a passing or transitional chord resolving somewhere else.');
INSERT INTO public.exercises VALUES (582, 'chord', 'Major 7th', 'What type of chord is this?', 'medium', '{"type":"maj7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Major 7th', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (583, 'chord', 'Minor 7th', 'What type of chord is this?', 'medium', '{"type":"min7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Minor 7th', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (584, 'chord', 'Augmented Triad', 'What type of chord is this?', 'medium', '{"type":"aug"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented"]', 'Augmented', 1783444284, 1783444284, 'An augmented chord raises the 5th of a major triad by a half-step, so both outer intervals become major 3rds. That symmetry gives it a restless, unresolved, almost dreamlike quality, often used to create tension right before a resolution.');
INSERT INTO public.exercises VALUES (585, 'chord', 'Major Chord', 'What type of chord is this?', 'hard', '{"type":"major"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major', 1783444284, 1783444284, 'A major chord is built from a root, major 3rd, and perfect 5th, giving it the bright, stable, ''happy'' sound that anchors most Western music. It''s the most common chord type and the natural resting point in a major key.');
INSERT INTO public.exercises VALUES (586, 'chord', 'Minor Chord', 'What type of chord is this?', 'hard', '{"type":"minor"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Minor', 1783444284, 1783444284, 'A minor chord swaps the major 3rd for a minor 3rd, keeping the same root and perfect 5th. That single lowered note gives it a darker, more melancholic color, and it''s the natural resting point in a minor key.');
INSERT INTO public.exercises VALUES (587, 'chord', 'Dominant 7th', 'What type of chord is this?', 'hard', '{"type":"dom7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Dominant 7th', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (588, 'chord', 'Diminished Triad', 'What type of chord is this?', 'hard', '{"type":"dim"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Diminished', 1783444284, 1783444284, 'A diminished chord stacks two minor 3rds on top of each other, giving every interval in the chord a tense, unstable quality. It has no strong ''home'' feeling of its own and almost always functions as a passing or transitional chord resolving somewhere else.');
INSERT INTO public.exercises VALUES (589, 'chord', 'Major 7th', 'What type of chord is this?', 'hard', '{"type":"maj7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major 7th', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (590, 'chord', 'Minor 7th', 'What type of chord is this?', 'hard', '{"type":"min7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Minor 7th', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (591, 'chord', 'Augmented Triad', 'What type of chord is this?', 'hard', '{"type":"aug"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Augmented', 1783444284, 1783444284, 'An augmented chord raises the 5th of a major triad by a half-step, so both outer intervals become major 3rds. That symmetry gives it a restless, unresolved, almost dreamlike quality, often used to create tension right before a resolution.');
INSERT INTO public.exercises VALUES (592, 'chord', 'Diminished 7th', 'What type of chord is this?', 'hard', '{"type":"dim7"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Diminished 7th', 1783444284, 1783444284, 'A diminished 7th chord stacks three minor 3rds in a row, dividing the octave perfectly evenly into four equal parts. That symmetry makes it maximally unstable and highly flexible for modulating between distant keys, a favorite trick in classical and jazz harmony.');
INSERT INTO public.exercises VALUES (593, 'chord', 'Half-Diminished 7th', 'What type of chord is this?', 'hard', '{"type":"min7b5"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Half-Diminished', 1783444284, 1783444284, 'A half-diminished chord (m7♭5) is a diminished triad with a minor 7th added instead of a diminished 7th, making it slightly less tense than a fully diminished chord. It''s best known as the ii chord in minor-key ii-V-i progressions in jazz.');
INSERT INTO public.exercises VALUES (594, 'chord', 'Major 9th', 'What type of chord is this?', 'hard', '{"type":"maj9"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major 9th', 1783444284, 1783444284, 'A major 9th chord extends a major 7th chord by adding the 9th (the 2nd scale degree, an octave up). That extra color note makes an already smooth major 7th sound even richer and more lush, common in jazz, neo-soul, and R&B.');
INSERT INTO public.exercises VALUES (595, 'chord', 'Minor 9th', 'What type of chord is this?', 'hard', '{"type":"min9"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Minor 9th', 1783444284, 1783444284, 'A minor 9th chord extends a minor 7th chord by adding the 9th on top, layering extra color onto its already dark, smooth sound. It''s widely used in jazz and neo-soul for a lush, sophisticated minor-key texture.');
INSERT INTO public.exercises VALUES (596, 'chord', 'Major 6th', 'What type of chord is this?', 'hard', '{"type":"maj6"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major 6th', 1783444284, 1783444284, 'A major 6th chord replaces a major 7th chord''s 7th with the 6th scale degree instead, giving it a bright, open, slightly retro sound without the 7th''s tension. It was a signature sound of swing-era and early jazz endings.');
INSERT INTO public.exercises VALUES (597, 'chord', 'Minor 6th', 'What type of chord is this?', 'hard', '{"type":"min6"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Minor 6th', 1783444284, 1783444284, 'A minor 6th chord adds the 6th scale degree (rather than a 7th) on top of a minor triad, giving it a slightly unresolved, wistful color distinct from a plain minor 7th. It shows up often in jazz and film-score minor-key passages.');
INSERT INTO public.exercises VALUES (598, 'chord', 'Suspended 4th', 'What type of chord is this?', 'hard', '{"type":"sus4"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Sus4', 1783444284, 1783444284, 'A suspended 4th chord replaces a chord''s 3rd with a 4th, removing the note that normally defines whether a chord is major or minor. That missing 3rd creates an open, floating tension that usually wants to resolve back down to the 3rd.');
INSERT INTO public.exercises VALUES (599, 'chord', 'Suspended 9th', 'What type of chord is this?', 'hard', '{"type":"sus9"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Sus9', 1783444284, 1783444284, 'A sus9 chord (also called 9sus4) replaces a dominant 9th chord''s 3rd with a 4th, keeping the 7th and 9th on top. It has an open, ambiguous quality that avoids resolving to major or minor, often used in modern pop and jazz as a color chord on its own rather than a passing suspension.');
INSERT INTO public.exercises VALUES (600, 'chord', 'Major add2', 'What type of chord is this?', 'hard', '{"type":"add2"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major add2', 1783444284, 1783444284, 'A major add2 chord adds the 2nd scale degree on top of a plain major triad, without removing the 3rd (unlike a sus2 chord, which replaces it). That extra note adds a bright, open, slightly modern color while keeping the chord clearly major, common in pop and contemporary singer-songwriter music.');
INSERT INTO public.exercises VALUES (601, 'chord', 'Major add4', 'What type of chord is this?', 'hard', '{"type":"add4"}', '["Major","Minor","Dominant 7th","Diminished","Major 7th","Minor 7th","Augmented","Diminished 7th","Half-Diminished","Major 9th","Minor 9th","Major 6th","Minor 6th","Sus4","Sus9","Major add2","Major add4"]', 'Major add4', 1783444284, 1783444284, 'A major add4 chord adds the perfect 4th on top of a plain major triad, without removing the 3rd (unlike a sus4 chord, which replaces it). The 3rd and 4th sitting a half-step apart create a bit of inner tension, giving the chord a bright but slightly unresolved, open color.');
INSERT INTO public.exercises VALUES (602, 'chord', 'Major Chord — 1st Inversion', 'What chord and inversion is this?', 'medium', '{"type":"major","inversion":1,"topic":"inversions"}', '["Major - Root Position","Major - 1st Inversion","Major - 2nd Inversion","Minor - Root Position","Minor - 1st Inversion","Minor - 2nd Inversion"]', 'Major - 1st Inversion', 1783444284, 1783444284, 'A major chord is built from a root, major 3rd, and perfect 5th, giving it the bright, stable, ''happy'' sound that anchors most Western music. It''s the most common chord type and the natural resting point in a major key.');
INSERT INTO public.exercises VALUES (603, 'chord', 'Major Chord — 2nd Inversion', 'What chord and inversion is this?', 'medium', '{"type":"major","inversion":2,"topic":"inversions"}', '["Major - Root Position","Major - 1st Inversion","Major - 2nd Inversion","Minor - Root Position","Minor - 1st Inversion","Minor - 2nd Inversion"]', 'Major - 2nd Inversion', 1783444284, 1783444284, 'A major chord is built from a root, major 3rd, and perfect 5th, giving it the bright, stable, ''happy'' sound that anchors most Western music. It''s the most common chord type and the natural resting point in a major key.');
INSERT INTO public.exercises VALUES (604, 'chord', 'Minor Chord — 1st Inversion', 'What chord and inversion is this?', 'medium', '{"type":"minor","inversion":1,"topic":"inversions"}', '["Major - Root Position","Major - 1st Inversion","Major - 2nd Inversion","Minor - Root Position","Minor - 1st Inversion","Minor - 2nd Inversion"]', 'Minor - 1st Inversion', 1783444284, 1783444284, 'A minor chord swaps the major 3rd for a minor 3rd, keeping the same root and perfect 5th. That single lowered note gives it a darker, more melancholic color, and it''s the natural resting point in a minor key.');
INSERT INTO public.exercises VALUES (605, 'chord', 'Minor Chord — 2nd Inversion', 'What chord and inversion is this?', 'medium', '{"type":"minor","inversion":2,"topic":"inversions"}', '["Major - Root Position","Major - 1st Inversion","Major - 2nd Inversion","Minor - Root Position","Minor - 1st Inversion","Minor - 2nd Inversion"]', 'Minor - 2nd Inversion', 1783444284, 1783444284, 'A minor chord swaps the major 3rd for a minor 3rd, keeping the same root and perfect 5th. That single lowered note gives it a darker, more melancholic color, and it''s the natural resting point in a minor key.');
INSERT INTO public.exercises VALUES (606, 'chord', 'Dominant 7th Chord — Root Position', 'What chord and inversion is this?', 'hard', '{"type":"dom7","inversion":0,"topic":"inversions"}', '["Dominant 7th - Root Position","Dominant 7th - 1st Inversion","Dominant 7th - 2nd Inversion","Dominant 7th - 3rd Inversion","Major 7th - Root Position","Minor 7th - Root Position"]', 'Dominant 7th - Root Position', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (607, 'chord', 'Dominant 7th Chord — 1st Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dom7","inversion":1,"topic":"inversions"}', '["Dominant 7th - Root Position","Dominant 7th - 1st Inversion","Dominant 7th - 2nd Inversion","Dominant 7th - 3rd Inversion","Major 7th - 1st Inversion","Minor 7th - 1st Inversion"]', 'Dominant 7th - 1st Inversion', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (608, 'chord', 'Dominant 7th Chord — 2nd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dom7","inversion":2,"topic":"inversions"}', '["Dominant 7th - Root Position","Dominant 7th - 1st Inversion","Dominant 7th - 2nd Inversion","Dominant 7th - 3rd Inversion","Major 7th - 2nd Inversion","Minor 7th - 2nd Inversion"]', 'Dominant 7th - 2nd Inversion', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (609, 'chord', 'Dominant 7th Chord — 3rd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dom7","inversion":3,"topic":"inversions"}', '["Dominant 7th - Root Position","Dominant 7th - 1st Inversion","Dominant 7th - 2nd Inversion","Dominant 7th - 3rd Inversion","Major 7th - 3rd Inversion","Minor 7th - 3rd Inversion"]', 'Dominant 7th - 3rd Inversion', 1783444284, 1783444284, 'A dominant 7th chord is a major triad with a minor 7th added on top, creating tension that wants to resolve down a fifth to the tonic. It''s the defining sound of the V chord in both major and minor keys, and the backbone of blues and jazz.');
INSERT INTO public.exercises VALUES (610, 'chord', 'Major 7th Chord — Root Position', 'What chord and inversion is this?', 'hard', '{"type":"maj7","inversion":0,"topic":"inversions"}', '["Major 7th - Root Position","Major 7th - 1st Inversion","Major 7th - 2nd Inversion","Major 7th - 3rd Inversion","Dominant 7th - Root Position","Minor 7th - Root Position"]', 'Major 7th - Root Position', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (611, 'chord', 'Major 7th Chord — 1st Inversion', 'What chord and inversion is this?', 'hard', '{"type":"maj7","inversion":1,"topic":"inversions"}', '["Major 7th - Root Position","Major 7th - 1st Inversion","Major 7th - 2nd Inversion","Major 7th - 3rd Inversion","Dominant 7th - 1st Inversion","Minor 7th - 1st Inversion"]', 'Major 7th - 1st Inversion', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (612, 'chord', 'Major 7th Chord — 2nd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"maj7","inversion":2,"topic":"inversions"}', '["Major 7th - Root Position","Major 7th - 1st Inversion","Major 7th - 2nd Inversion","Major 7th - 3rd Inversion","Dominant 7th - 2nd Inversion","Minor 7th - 2nd Inversion"]', 'Major 7th - 2nd Inversion', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (613, 'chord', 'Major 7th Chord — 3rd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"maj7","inversion":3,"topic":"inversions"}', '["Major 7th - Root Position","Major 7th - 1st Inversion","Major 7th - 2nd Inversion","Major 7th - 3rd Inversion","Dominant 7th - 3rd Inversion","Minor 7th - 3rd Inversion"]', 'Major 7th - 3rd Inversion', 1783444284, 1783444284, 'A major 7th chord adds a major 7th on top of a major triad, one half-step below the octave. That extra note softens the chord''s brightness into something smoother and more sophisticated, giving it the dreamy, jazzy color heard in ballads and soul music.');
INSERT INTO public.exercises VALUES (614, 'chord', 'Minor 7th Chord — Root Position', 'What chord and inversion is this?', 'hard', '{"type":"min7","inversion":0,"topic":"inversions"}', '["Minor 7th - Root Position","Minor 7th - 1st Inversion","Minor 7th - 2nd Inversion","Minor 7th - 3rd Inversion","Major 7th - Root Position","Dominant 7th - Root Position"]', 'Minor 7th - Root Position', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (615, 'chord', 'Minor 7th Chord — 1st Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7","inversion":1,"topic":"inversions"}', '["Minor 7th - Root Position","Minor 7th - 1st Inversion","Minor 7th - 2nd Inversion","Minor 7th - 3rd Inversion","Major 7th - 1st Inversion","Dominant 7th - 1st Inversion"]', 'Minor 7th - 1st Inversion', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (616, 'chord', 'Minor 7th Chord — 2nd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7","inversion":2,"topic":"inversions"}', '["Minor 7th - Root Position","Minor 7th - 1st Inversion","Minor 7th - 2nd Inversion","Minor 7th - 3rd Inversion","Major 7th - 2nd Inversion","Dominant 7th - 2nd Inversion"]', 'Minor 7th - 2nd Inversion', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (617, 'chord', 'Minor 7th Chord — 3rd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7","inversion":3,"topic":"inversions"}', '["Minor 7th - Root Position","Minor 7th - 1st Inversion","Minor 7th - 2nd Inversion","Minor 7th - 3rd Inversion","Major 7th - 3rd Inversion","Dominant 7th - 3rd Inversion"]', 'Minor 7th - 3rd Inversion', 1783444284, 1783444284, 'A minor 7th chord adds a minor 7th on top of a minor triad, blending the minor chord''s darker color with a smoother, less resolved quality than a plain minor triad. It''s a staple of jazz, R&B, and soul, especially in ii chords.');
INSERT INTO public.exercises VALUES (618, 'chord', 'Diminished 7th Chord — Root Position', 'What chord and inversion is this?', 'hard', '{"type":"dim7","inversion":0,"topic":"inversions"}', '["Diminished 7th - Root Position","Diminished 7th - 1st Inversion","Diminished 7th - 2nd Inversion","Diminished 7th - 3rd Inversion","Half-Diminished - Root Position","Minor 7th - Root Position"]', 'Diminished 7th - Root Position', 1783444284, 1783444284, 'A diminished 7th chord stacks three minor 3rds in a row, dividing the octave perfectly evenly into four equal parts. That symmetry makes it maximally unstable and highly flexible for modulating between distant keys, a favorite trick in classical and jazz harmony.');
INSERT INTO public.exercises VALUES (619, 'chord', 'Diminished 7th Chord — 1st Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dim7","inversion":1,"topic":"inversions"}', '["Diminished 7th - Root Position","Diminished 7th - 1st Inversion","Diminished 7th - 2nd Inversion","Diminished 7th - 3rd Inversion","Half-Diminished - 1st Inversion","Minor 7th - 1st Inversion"]', 'Diminished 7th - 1st Inversion', 1783444284, 1783444284, 'A diminished 7th chord stacks three minor 3rds in a row, dividing the octave perfectly evenly into four equal parts. That symmetry makes it maximally unstable and highly flexible for modulating between distant keys, a favorite trick in classical and jazz harmony.');
INSERT INTO public.exercises VALUES (620, 'chord', 'Diminished 7th Chord — 2nd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dim7","inversion":2,"topic":"inversions"}', '["Diminished 7th - Root Position","Diminished 7th - 1st Inversion","Diminished 7th - 2nd Inversion","Diminished 7th - 3rd Inversion","Half-Diminished - 2nd Inversion","Minor 7th - 2nd Inversion"]', 'Diminished 7th - 2nd Inversion', 1783444284, 1783444284, 'A diminished 7th chord stacks three minor 3rds in a row, dividing the octave perfectly evenly into four equal parts. That symmetry makes it maximally unstable and highly flexible for modulating between distant keys, a favorite trick in classical and jazz harmony.');
INSERT INTO public.exercises VALUES (621, 'chord', 'Diminished 7th Chord — 3rd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"dim7","inversion":3,"topic":"inversions"}', '["Diminished 7th - Root Position","Diminished 7th - 1st Inversion","Diminished 7th - 2nd Inversion","Diminished 7th - 3rd Inversion","Half-Diminished - 3rd Inversion","Minor 7th - 3rd Inversion"]', 'Diminished 7th - 3rd Inversion', 1783444284, 1783444284, 'A diminished 7th chord stacks three minor 3rds in a row, dividing the octave perfectly evenly into four equal parts. That symmetry makes it maximally unstable and highly flexible for modulating between distant keys, a favorite trick in classical and jazz harmony.');
INSERT INTO public.exercises VALUES (622, 'chord', 'Half-Diminished Chord — Root Position', 'What chord and inversion is this?', 'hard', '{"type":"min7b5","inversion":0,"topic":"inversions"}', '["Half-Diminished - Root Position","Half-Diminished - 1st Inversion","Half-Diminished - 2nd Inversion","Half-Diminished - 3rd Inversion","Diminished 7th - Root Position","Minor 7th - Root Position"]', 'Half-Diminished - Root Position', 1783444284, 1783444284, 'A half-diminished chord (m7♭5) is a diminished triad with a minor 7th added instead of a diminished 7th, making it slightly less tense than a fully diminished chord. It''s best known as the ii chord in minor-key ii-V-i progressions in jazz.');
INSERT INTO public.exercises VALUES (623, 'chord', 'Half-Diminished Chord — 1st Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7b5","inversion":1,"topic":"inversions"}', '["Half-Diminished - Root Position","Half-Diminished - 1st Inversion","Half-Diminished - 2nd Inversion","Half-Diminished - 3rd Inversion","Diminished 7th - 1st Inversion","Minor 7th - 1st Inversion"]', 'Half-Diminished - 1st Inversion', 1783444284, 1783444284, 'A half-diminished chord (m7♭5) is a diminished triad with a minor 7th added instead of a diminished 7th, making it slightly less tense than a fully diminished chord. It''s best known as the ii chord in minor-key ii-V-i progressions in jazz.');
INSERT INTO public.exercises VALUES (624, 'chord', 'Half-Diminished Chord — 2nd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7b5","inversion":2,"topic":"inversions"}', '["Half-Diminished - Root Position","Half-Diminished - 1st Inversion","Half-Diminished - 2nd Inversion","Half-Diminished - 3rd Inversion","Diminished 7th - 2nd Inversion","Minor 7th - 2nd Inversion"]', 'Half-Diminished - 2nd Inversion', 1783444284, 1783444284, 'A half-diminished chord (m7♭5) is a diminished triad with a minor 7th added instead of a diminished 7th, making it slightly less tense than a fully diminished chord. It''s best known as the ii chord in minor-key ii-V-i progressions in jazz.');
INSERT INTO public.exercises VALUES (625, 'chord', 'Half-Diminished Chord — 3rd Inversion', 'What chord and inversion is this?', 'hard', '{"type":"min7b5","inversion":3,"topic":"inversions"}', '["Half-Diminished - Root Position","Half-Diminished - 1st Inversion","Half-Diminished - 2nd Inversion","Half-Diminished - 3rd Inversion","Diminished 7th - 3rd Inversion","Minor 7th - 3rd Inversion"]', 'Half-Diminished - 3rd Inversion', 1783444284, 1783444284, 'A half-diminished chord (m7♭5) is a diminished triad with a minor 7th added instead of a diminished 7th, making it slightly less tense than a fully diminished chord. It''s best known as the ii chord in minor-key ii-V-i progressions in jazz.');
INSERT INTO public.exercises VALUES (358, 'chord', 'Major 7th', 'What type of chord is this?', 'jazz', '{"type":"maj7","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (359, 'chord', 'Major 9th', 'What type of chord is this?', 'jazz', '{"type":"maj9","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 9th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (360, 'chord', 'Major 7th ♯11 (Lydian)', 'What type of chord is this?', 'jazz', '{"type":"maj7s11","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 7th #11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (361, 'chord', 'Major 6th', 'What type of chord is this?', 'jazz', '{"type":"maj6","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 6th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (362, 'chord', 'Major 6/9', 'What type of chord is this?', 'jazz', '{"type":"maj6_9","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 6/9', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (363, 'chord', 'Major 13th', 'What type of chord is this?', 'jazz', '{"type":"maj13","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 13th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (364, 'chord', 'Augmented Major 7th', 'What type of chord is this?', 'jazz', '{"type":"augMaj7","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Augmented Major 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (365, 'chord', 'Major 9th ♯11', 'What type of chord is this?', 'jazz', '{"type":"maj9s11","family":"major"}', '["Major 7th","Major 9th","Major 7th #11","Major 9th #11","Major 13th","Major 6th","Major 6/9","Augmented Major 7th"]', 'Major 9th #11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (366, 'chord', 'Minor 9th', 'What type of chord is this?', 'jazz', '{"type":"min9","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor 9th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (367, 'chord', 'Minor 11th', 'What type of chord is this?', 'jazz', '{"type":"min11","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor 11th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (368, 'chord', 'Minor 13th', 'What type of chord is this?', 'jazz', '{"type":"min13","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor 13th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (369, 'chord', 'Minor-Major 7th', 'What type of chord is this?', 'jazz', '{"type":"minMaj7","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor-Major 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (370, 'chord', 'Minor-Major 9th', 'What type of chord is this?', 'jazz', '{"type":"minMaj9","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor-Major 9th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (371, 'chord', 'Minor 6th', 'What type of chord is this?', 'jazz', '{"type":"min6","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor 6th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (372, 'chord', 'Minor 7th', 'What type of chord is this?', 'jazz', '{"type":"min7","family":"minor"}', '["Minor 7th","Minor 9th","Minor 11th","Minor 13th","Minor-Major 7th","Minor-Major 9th","Minor 6th"]', 'Minor 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (373, 'chord', 'Dominant 9th', 'What type of chord is this?', 'jazz', '{"type":"dom9","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 9th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (374, 'chord', 'Dominant 13th', 'What type of chord is this?', 'jazz', '{"type":"dom13","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 13th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (375, 'chord', 'Dominant 7th ♯11', 'What type of chord is this?', 'jazz', '{"type":"dom7s11","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 7th #11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (376, 'chord', 'Dominant 9th ♯11', 'What type of chord is this?', 'jazz', '{"type":"dom9s11","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 9th #11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (377, 'chord', 'Dominant 13th ♯11', 'What type of chord is this?', 'jazz', '{"type":"dom13s11","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 13th #11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (378, 'chord', 'Dominant 9th', 'What type of chord is this?', 'jazz', '{"type":"dom9","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 9th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (379, 'chord', 'Dominant 13th', 'What type of chord is this?', 'jazz', '{"type":"dom13","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 13th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (380, 'chord', 'Dominant 7th', 'What type of chord is this?', 'jazz', '{"type":"dom7","family":"dominant"}', '["Dominant 7th","Dominant 9th","Dominant 13th","Dominant 7th #11","Dominant 9th #11","Dominant 13th #11"]', 'Dominant 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (381, 'chord', '7♯9 (Hendrix Chord)', 'What type of chord is this?', 'jazz', '{"type":"dom7s9","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♯9', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (382, 'chord', '7♭9', 'What type of chord is this?', 'jazz', '{"type":"dom7b9","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♭9', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (383, 'chord', '7♭13', 'What type of chord is this?', 'jazz', '{"type":"dom7b13","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♭13', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (384, 'chord', '7♭9♭13', 'What type of chord is this?', 'jazz', '{"type":"dom7b9b13","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♭9♭13', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (385, 'chord', '7♯9♭13', 'What type of chord is this?', 'jazz', '{"type":"dom7s9b13","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♯9♭13', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (386, 'chord', '7♭9♯11', 'What type of chord is this?', 'jazz', '{"type":"dom7b9s11","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♭9♯11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (387, 'chord', '7♯9♯11', 'What type of chord is this?', 'jazz', '{"type":"dom7s9s11","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', '7♯9♯11', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (388, 'chord', 'Augmented 7th (7♯5)', 'What type of chord is this?', 'jazz', '{"type":"dom7s5","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', 'Augmented 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (389, 'chord', 'Dominant 7th ♭5', 'What type of chord is this?', 'jazz', '{"type":"dom7b5","family":"altered"}', '["7♭9","7♯9","7♭13","7♭9♭13","7♯9♭13","7♭9♯11","7♯9♯11","Augmented 7th","Dominant 7th ♭5"]', 'Dominant 7th ♭5', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (390, 'chord', '7sus4', 'What type of chord is this?', 'jazz', '{"type":"sus7","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '7sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (391, 'chord', '9sus4', 'What type of chord is this?', 'jazz', '{"type":"sus9","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '9sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (392, 'chord', '13sus4', 'What type of chord is this?', 'jazz', '{"type":"sus13","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '13sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (393, 'chord', '7sus4', 'What type of chord is this?', 'jazz', '{"type":"sus7","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '7sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (394, 'chord', '9sus4', 'What type of chord is this?', 'jazz', '{"type":"sus9","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '9sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (395, 'chord', '13sus4', 'What type of chord is this?', 'jazz', '{"type":"sus13","family":"suspended"}', '["7sus4","9sus4","13sus4"]', '13sus4', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (396, 'chord', 'Diminished 7th', 'What type of chord is this?', 'jazz', '{"type":"dim7","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Diminished 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (397, 'chord', 'Half-Diminished (m7♭5)', 'What type of chord is this?', 'jazz', '{"type":"min7b5","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Half-Diminished', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (398, 'chord', 'Diminished 7th', 'What type of chord is this?', 'jazz', '{"type":"dim7","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Diminished 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (399, 'chord', 'Half-Diminished (m7♭5)', 'What type of chord is this?', 'jazz', '{"type":"min7b5","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Half-Diminished', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (400, 'chord', 'Diminished 7th', 'What type of chord is this?', 'jazz', '{"type":"dim7","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Diminished 7th', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (401, 'chord', 'Half-Diminished (m7♭5)', 'What type of chord is this?', 'jazz', '{"type":"min7b5","family":"diminished"}', '["Half-Diminished","Diminished 7th"]', 'Half-Diminished', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (402, 'progression', 'The Classic I - IV - V', 'What chord progression is this?', 'easy', '{"key":"C","chords":[["C4","E4","G4"],["F4","A4","C5"],["G4","B4","D5"]],"romanNumerals":["I","IV","V"],"tempo":80}', '["I - IV - V","I - V - vi - IV","I - IV - V - I","I - V - IV - I","I - I - IV - V","I - vi - IV - V","vi - IV - I - V","I - IV - vi - V"]', 'I - IV - V', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (403, 'progression', 'Pop Progression I - V - vi - IV', 'What chord progression is this?', 'easy', '{"key":"C","chords":[["C4","E4","G4"],["G4","B4","D5"],["A4","C5","E5"],["F4","A4","C5"]],"romanNumerals":["I","V","vi","IV"],"tempo":76}', '["I - IV - V","I - V - vi - IV","I - IV - V - I","I - V - IV - I","I - I - IV - V","I - vi - IV - V","vi - IV - I - V","I - IV - vi - V"]', 'I - V - vi - IV', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (404, 'progression', 'Jazz ii - V - I', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["D4","F4","A4","C5"],["G4","B4","D5","F5"],["C4","E4","G4","B4"]],"romanNumerals":["ii","V","I"],"tempo":80}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'ii - V - I', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (405, 'progression', '50s Progression I - vi - IV - V', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C4","E4","G4"],["A4","C5","E5"],["F4","A4","C5"],["G4","B4","D5"]],"romanNumerals":["I","vi","IV","V"],"tempo":80}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - vi - IV - V', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (406, 'progression', 'I - IV - vi - V', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C4","E4","G4"],["F4","A4","C5"],["A4","C5","E5"],["G4","B4","D5"]],"romanNumerals":["I","IV","vi","V"],"tempo":80}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - IV - vi - V', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (407, 'progression', 'vi - IV - I - V', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["A4","C5","E5"],["F4","A4","C5"],["C4","E4","G4"],["G4","B4","D5"]],"romanNumerals":["vi","IV","I","V"],"tempo":80}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'vi - IV - I - V', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (408, 'progression', 'I - III - IV - iv (minor mixture)', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["C4","E4","G4"],["E4","G#4","B4"],["F4","A4","C5"],["F4","G#4","C5"]],"romanNumerals":["I","III","IV","iv"],"tempo":72}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'I - III - IV - iv', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (409, 'progression', 'ii - IV - I - V', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["D4","F4","A4"],["F4","A4","C5"],["C4","E4","G4"],["G4","B4","D5"]],"romanNumerals":["ii","IV","I","V"],"tempo":80}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'ii - IV - I - V', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (410, 'progression', 'ii7 - V7 - Imaj7 in C', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["D3","F3","A3","C4"],["G3","B3","D4","F4"],["C3","E3","G3","B3"]],"romanNumerals":["ii7","V7","Imaj7"],"tempo":80}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'ii7 - V7 - Imaj7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (411, 'progression', 'Minor ii-V-i in Am', 'What chord progression is this?', 'jazz', '{"key":"Am","chords":[["B3","D4","F4","A4"],["E3","G#3","B3","D4","F4"],["A3","C4","E4","G4"]],"romanNumerals":["iim7b5","V7b9","im7"],"tempo":76}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'iim7b5 - V7b9 - im7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (412, 'progression', 'Rhythm Changes A in C', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["C3","E3","G3","B3"],["A3","C#4","E4","G4"],["D3","F3","A3","C4"],["G3","B3","D4","F4"]],"romanNumerals":["Imaj7","VI7","ii7","V7"],"tempo":90}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'Imaj7 - VI7 - ii7 - V7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (413, 'progression', 'Jazz Blues in G', 'What chord progression is this?', 'jazz', '{"key":"G","chords":[["G3","B3","D4","F4"],["C3","E3","G3","A#3"],["G3","B3","D4","F4"],["D3","F#3","A3","C4"]],"romanNumerals":["I7","IV7","I7","V7"],"tempo":84}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'I7 - IV7 - I7 - V7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (414, 'progression', 'Tritone Sub in C', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["D3","F3","A3","C4"],["C#3","F3","G#3","B3"],["C3","E3","G3","B3"]],"romanNumerals":["ii7","bII7","Imaj7"],"tempo":72}', '["ii7 - bII7 - Imaj7","Imaj7 - IVmaj7 - iii7 - VI7","ii7 - V7 - iii7 - VI7","im7 - IV7 - bVImaj7 - V7","Imaj7 - bVImaj7 - bIImaj7 - V7","ii7 - V7 - Imaj7","Imaj7 - VI7 - ii7 - V7","iim7b5 - V7b9 - im7"]', 'ii7 - bII7 - Imaj7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (415, 'progression', 'Diatonic Cycle in C', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["E3","G3","B3","D4"],["A3","C#4","E4","G4"],["D3","F3","A3","C4"],["G3","B3","D4","F4"]],"romanNumerals":["iii7","VI7","ii7","V7"],"tempo":80}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'iii7 - VI7 - ii7 - V7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (416, 'progression', 'Imaj7-IVmaj7-iii7-VI7 in C', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["C3","E3","G3","B3"],["F3","A3","C4","E4"],["E3","G3","B3","D4"],["A3","C#4","E4","G4"]],"romanNumerals":["Imaj7","IVmaj7","iii7","VI7"],"tempo":76}', '["ii7 - bII7 - Imaj7","Imaj7 - IVmaj7 - iii7 - VI7","ii7 - V7 - iii7 - VI7","im7 - IV7 - bVImaj7 - V7","Imaj7 - bVImaj7 - bIImaj7 - V7","ii7 - V7 - Imaj7","Imaj7 - VI7 - ii7 - V7","iim7b5 - V7b9 - im7"]', 'Imaj7 - IVmaj7 - iii7 - VI7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (417, 'progression', 'Minor Jazz Descent in Am', 'What chord progression is this?', 'jazz', '{"key":"Am","chords":[["A3","C4","E4","G4"],["G3","B3","D4","F4"],["F3","A3","C4","E4"],["E3","G#3","B3","D4"]],"romanNumerals":["im7","bVII7","bVI7","V7"],"tempo":72}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'im7 - bVII7 - bVI7 - V7', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (418, 'scale', 'Major Scale', 'What scale type is this?', 'easy', '{"type":"major"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Major', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (419, 'scale', 'Major Scale', 'What scale type is this?', 'easy', '{"type":"major"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Major', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (420, 'scale', 'Harmonic Minor Scale', 'What scale type is this?', 'easy', '{"type":"harmonic_minor"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Harmonic Minor', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (421, 'scale', 'Blues Scale', 'What scale type is this?', 'medium', '{"type":"blues"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Blues', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (422, 'scale', 'Pentatonic Major Scale', 'What scale type is this?', 'medium', '{"type":"pentatonic_major"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Pentatonic Major', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (423, 'scale', 'Dorian Scale', 'What scale type is this?', 'medium', '{"type":"dorian"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Dorian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (424, 'scale', 'Mixolydian Scale', 'What scale type is this?', 'medium', '{"type":"mixolydian"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Mixolydian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (425, 'scale', 'Blues Scale', 'What scale type is this?', 'hard', '{"type":"blues"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Blues', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (426, 'scale', 'Harmonic Minor Scale', 'What scale type is this?', 'hard', '{"type":"harmonic_minor"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Harmonic Minor', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (427, 'scale', 'Dorian Scale', 'What scale type is this?', 'hard', '{"type":"dorian"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Dorian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (428, 'scale', 'Mixolydian Scale', 'What scale type is this?', 'hard', '{"type":"mixolydian"}', '["Major","Dorian","Mixolydian","Blues","Pentatonic Major","Harmonic Minor"]', 'Mixolydian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (429, 'scale', 'Melodic Minor Scale', 'What scale type is this?', 'jazz', '{"type":"melodic_minor"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Melodic Minor', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (430, 'scale', 'Lydian Scale', 'What scale type is this?', 'jazz', '{"type":"lydian"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Lydian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (431, 'scale', 'Lydian Dominant Scale', 'What scale type is this?', 'jazz', '{"type":"lydian_b7"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Lydian Dominant', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (432, 'scale', 'Altered Scale', 'What scale type is this?', 'jazz', '{"type":"altered"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Altered', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (433, 'scale', 'Melodic Minor Scale', 'What scale type is this?', 'jazz', '{"type":"melodic_minor"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Melodic Minor', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (434, 'scale', 'Lydian Scale', 'What scale type is this?', 'jazz', '{"type":"lydian"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Lydian', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (435, 'scale', 'Lydian Dominant Scale', 'What scale type is this?', 'jazz', '{"type":"lydian_b7"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Lydian Dominant', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (436, 'scale', 'Altered Scale', 'What scale type is this?', 'jazz', '{"type":"altered"}', '["Major","Melodic Minor","Lydian","Lydian Dominant","Altered","Harmonic Minor","Dorian"]', 'Altered', 1782855320, 1782855320, NULL);
INSERT INTO public.exercises VALUES (626, 'interval', 'Unison', 'What interval is this?', 'easy', '{"semitones":0,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Unison', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (627, 'interval', 'Minor 2nd', 'What interval is this?', 'easy', '{"semitones":1,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 2nd', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (628, 'interval', 'Major 2nd', 'What interval is this?', 'easy', '{"semitones":2,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 2nd', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (629, 'interval', 'Minor 3rd', 'What interval is this?', 'easy', '{"semitones":3,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 3rd', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (630, 'interval', 'Major 3rd', 'What interval is this?', 'easy', '{"semitones":4,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 3rd', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (631, 'interval', 'Perfect 4th', 'What interval is this?', 'easy', '{"semitones":5,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Perfect 4th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (632, 'interval', 'Tritone', 'What interval is this?', 'easy', '{"semitones":6,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Tritone', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (633, 'interval', 'Perfect 5th', 'What interval is this?', 'easy', '{"semitones":7,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Perfect 5th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (634, 'interval', 'Minor 6th', 'What interval is this?', 'medium', '{"semitones":8,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 6th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (635, 'interval', 'Major 6th', 'What interval is this?', 'medium', '{"semitones":9,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 6th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (636, 'interval', 'Minor 7th', 'What interval is this?', 'medium', '{"semitones":10,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 7th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (637, 'interval', 'Major 7th', 'What interval is this?', 'medium', '{"semitones":11,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 7th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (638, 'interval', 'Octave', 'What interval is this?', 'medium', '{"semitones":12,"playMode":"harmonic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Octave', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (639, 'interval', 'Minor 9th', 'What interval is this?', 'hard', '{"semitones":13,"playMode":"melodic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 9th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (640, 'interval', 'Major 9th', 'What interval is this?', 'hard', '{"semitones":14,"playMode":"melodic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 9th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (641, 'interval', 'Minor 10th', 'What interval is this?', 'hard', '{"semitones":15,"playMode":"melodic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Minor 10th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (642, 'interval', 'Major 10th', 'What interval is this?', 'hard', '{"semitones":16,"playMode":"melodic"}', '["Unison","Minor 2nd","Major 2nd","Minor 3rd","Major 3rd","Perfect 4th","Tritone","Perfect 5th","Minor 6th","Major 6th","Minor 7th","Major 7th","Octave","Minor 9th","Major 9th","Minor 10th","Major 10th"]', 'Major 10th', 1783445940, 1783445940, NULL);
INSERT INTO public.exercises VALUES (472, 'progression', 'Cadential Turnaround I - IV - V - I', 'What chord progression is this?', 'easy', '{"key":"C","chords":[["C4","E4","G4"],["F4","A4","C5"],["G4","B4","D5"],["C4","E4","G4"]],"romanNumerals":["I","IV","V","I"],"tempo":80,"topic":"pop"}', '["I - IV - V","I - V - vi - IV","I - IV - V - I","I - V - IV - I","I - I - IV - V","I - vi - IV - V","vi - IV - I - V","I - IV - vi - V"]', 'I - IV - V - I', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (473, 'progression', 'Rock Cadence I - V - IV - I', 'What chord progression is this?', 'easy', '{"key":"C","chords":[["C4","E4","G4"],["G4","B4","D5"],["F4","A4","C5"],["C4","E4","G4"]],"romanNumerals":["I","V","IV","I"],"tempo":80,"topic":"pop"}', '["I - IV - V","I - V - vi - IV","I - IV - V - I","I - V - IV - I","I - I - IV - V","I - vi - IV - V","vi - IV - I - V","I - IV - vi - V"]', 'I - V - IV - I', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (474, 'progression', 'Extended Tonic I - I - IV - V', 'What chord progression is this?', 'easy', '{"key":"C","chords":[["C4","E4","G4"],["C4","E4","G4"],["F4","A4","C5"],["G4","B4","D5"]],"romanNumerals":["I","I","IV","V"],"tempo":76,"topic":"pop"}', '["I - IV - V","I - V - vi - IV","I - IV - V - I","I - V - IV - I","I - I - IV - V","I - vi - IV - V","vi - IV - I - V","I - IV - vi - V"]', 'I - I - IV - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (475, 'progression', 'Mediant Bridge I - iii - IV - V', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C3","E3","G3"],["E3","G3","B3"],["F3","A3","C4"],["G3","B3","D4"]],"romanNumerals":["I","iii","IV","V"],"tempo":76,"topic":"diatonic"}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - iii - IV - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (476, 'progression', 'Mixolydian I - bVII - IV - I', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C3","E3","G3"],["Bb3","D4","F4"],["F3","A3","C4"],["C3","E3","G3"]],"romanNumerals":["I","bVII","IV","I"],"tempo":80,"topic":"modal"}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - bVII - IV - I', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (477, 'progression', 'Natural Minor i - VII - VI - VII', 'What chord progression is this?', 'medium', '{"key":"Am","chords":[["A3","C4","E4"],["G3","B3","D4"],["F3","A3","C4"],["G3","B3","D4"]],"romanNumerals":["i","VII","VI","VII"],"tempo":76,"topic":"minor"}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'i - VII - VI - VII', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (478, 'progression', 'Circle of Fifths I - vi - ii - V', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C3","E3","G3"],["A3","C4","E4"],["D3","F3","A3"],["G3","B3","D4"]],"romanNumerals":["I","vi","ii","V"],"tempo":80,"topic":"diatonic"}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - vi - ii - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (479, 'progression', 'Descending I - IV - iii - vi', 'What chord progression is this?', 'medium', '{"key":"C","chords":[["C3","E3","G3"],["F3","A3","C4"],["E3","G3","B3"],["A3","C4","E4"]],"romanNumerals":["I","IV","iii","vi"],"tempo":80,"topic":"diatonic"}', '["ii - V - I","I - iii - IV - V","I - bVII - IV - I","i - VII - VI - VII","I - vi - ii - V","I - IV - iii - vi","I - vi - IV - V","I - IV - vi - V"]', 'I - IV - iii - vi', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (480, 'progression', 'Borrowed Chords I - bVI - bVII - I', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["C3","E3","G3"],["Ab3","C4","Eb4"],["Bb3","D4","F4"],["C3","E3","G3"]],"romanNumerals":["I","bVI","bVII","I"],"tempo":76,"topic":"modal"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'I - bVI - bVII - I', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (481, 'progression', 'Minor Subdominant IV - iv - I - V', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["F3","A3","C4"],["F3","Ab3","C4"],["C3","E3","G3"],["G3","B3","D4"]],"romanNumerals":["IV","iv","I","V"],"tempo":80,"topic":"diatonic"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'IV - iv - I - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (482, 'progression', 'Secondary Dominant I - II - IV - V', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["C3","E3","G3"],["D3","F#3","A3"],["F3","A3","C4"],["G3","B3","D4"]],"romanNumerals":["I","II","IV","V"],"tempo":80,"topic":"diatonic"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'I - II - IV - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (483, 'progression', 'Chromatic Two-Step bVI - bVII - I', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["Ab3","C4","Eb4"],["Bb3","D4","F4"],["C3","E3","G3"]],"romanNumerals":["bVI","bVII","I"],"tempo":72,"topic":"modal"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'bVI - bVII - I', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (484, 'progression', 'Harmonic Minor i - V7 - bVI - III', 'What chord progression is this?', 'hard', '{"key":"Am","chords":[["A3","C4","E4"],["E3","G#3","B3","D4"],["F3","A3","C4"],["C3","E3","G3"]],"romanNumerals":["i","V7","bVI","III"],"tempo":76,"topic":"minor"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'i - V7 - bVI - III', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (485, 'progression', 'Andalusian Descent I - bVII - bVI - V', 'What chord progression is this?', 'hard', '{"key":"C","chords":[["C3","E3","G3"],["Bb3","D4","F4"],["Ab3","C4","Eb4"],["G3","B3","D4"]],"romanNumerals":["I","bVII","bVI","V"],"tempo":76,"topic":"modal"}', '["I - III - IV - iv","ii - IV - I - V","I - bVI - bVII - I","IV - iv - I - V","I - II - IV - V","bVI - bVII - I","i - V7 - bVI - III","I - bVII - bVI - V"]', 'I - bVII - bVI - V', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (486, 'progression', 'Standard Ballad Imaj7 - I7 - IVmaj7 - iv7', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["C3","E3","G3","B3"],["C3","E3","G3","Bb3"],["F3","A3","C4","E4"],["F3","Ab3","C4","Eb4"]],"romanNumerals":["Imaj7","I7","IVmaj7","iv7"],"tempo":72,"topic":"jazz"}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'Imaj7 - I7 - IVmaj7 - iv7', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (487, 'progression', 'Forward Turnaround ii7 - V7 - iii7 - VI7', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["D3","F3","A3","C4"],["G3","B3","D4","F4"],["E3","G3","B3","D4"],["A3","C#4","E4","G4"]],"romanNumerals":["ii7","V7","iii7","VI7"],"tempo":80,"topic":"jazz"}', '["ii7 - bII7 - Imaj7","Imaj7 - IVmaj7 - iii7 - VI7","ii7 - V7 - iii7 - VI7","im7 - IV7 - bVImaj7 - V7","Imaj7 - bVImaj7 - bIImaj7 - V7","ii7 - V7 - Imaj7","Imaj7 - VI7 - ii7 - V7","iim7b5 - V7b9 - im7"]', 'ii7 - V7 - iii7 - VI7', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (488, 'progression', 'Minor Jazz im7 - IV7 - bVImaj7 - V7', 'What chord progression is this?', 'jazz', '{"key":"Am","chords":[["A3","C4","E4","G4"],["D3","F#3","A3","C4"],["F3","A3","C4","E4"],["E3","G#3","B3","D4"]],"romanNumerals":["im7","IV7","bVImaj7","V7"],"tempo":76,"topic":"jazz"}', '["ii7 - bII7 - Imaj7","Imaj7 - IVmaj7 - iii7 - VI7","ii7 - V7 - iii7 - VI7","im7 - IV7 - bVImaj7 - V7","Imaj7 - bVImaj7 - bIImaj7 - V7","ii7 - V7 - Imaj7","Imaj7 - VI7 - ii7 - V7","iim7b5 - V7b9 - im7"]', 'im7 - IV7 - bVImaj7 - V7', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (489, 'progression', 'Dominant Chain III7 - VI7 - II7 - V7', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["E3","G#3","B3","D4"],["A3","C#4","E4","G4"],["D3","F#3","A3","C4"],["G3","B3","D4","F4"]],"romanNumerals":["III7","VI7","II7","V7"],"tempo":84,"topic":"jazz"}', '["ii7 - V7 - Imaj7","iim7b5 - V7b9 - im7","Imaj7 - VI7 - ii7 - V7","I7 - IV7 - I7 - V7","im7 - bVII7 - bVI7 - V7","Imaj7 - I7 - IVmaj7 - iv7","iii7 - VI7 - ii7 - V7","III7 - VI7 - II7 - V7"]', 'III7 - VI7 - II7 - V7', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (490, 'progression', 'Chromatic Thirds Imaj7 - bVImaj7 - bIImaj7 - V7', 'What chord progression is this?', 'jazz', '{"key":"C","chords":[["C3","E3","G3","B3"],["Ab3","C4","Eb4","G4"],["Db3","F3","Ab3","C4"],["G3","B3","D4","F4"]],"romanNumerals":["Imaj7","bVImaj7","bIImaj7","V7"],"tempo":72,"topic":"jazz"}', '["ii7 - bII7 - Imaj7","Imaj7 - IVmaj7 - iii7 - VI7","ii7 - V7 - iii7 - VI7","im7 - IV7 - bVImaj7 - V7","Imaj7 - bVImaj7 - bIImaj7 - V7","ii7 - V7 - Imaj7","Imaj7 - VI7 - ii7 - V7","iim7b5 - V7b9 - im7"]', 'Imaj7 - bVImaj7 - bIImaj7 - V7', 1782855325, 1782855325, NULL);
INSERT INTO public.exercises VALUES (491, 'scale', 'Aeolian Scale', 'What scale type is this?', 'easy', '{"type":"aeolian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Aeolian (Minor)', 1782855327, 1782855327, NULL);
INSERT INTO public.exercises VALUES (492, 'scale', 'Aeolian Scale', 'What scale type is this?', 'medium', '{"type":"aeolian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Aeolian (Minor)', 1782855327, 1782855327, NULL);
INSERT INTO public.exercises VALUES (493, 'scale', 'Aeolian Scale', 'What scale type is this?', 'hard', '{"type":"aeolian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Aeolian (Minor)', 1782855327, 1782855327, NULL);
INSERT INTO public.exercises VALUES (494, 'scale', 'Phrygian Scale', 'What scale type is this?', 'medium', '{"type":"phrygian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Phrygian', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (495, 'scale', 'Phrygian Scale', 'What scale type is this?', 'hard', '{"type":"phrygian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Phrygian', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (496, 'scale', 'Locrian Scale', 'What scale type is this?', 'hard', '{"type":"locrian","topic":"major_modes"}', '["Major","Dorian","Phrygian","Lydian","Mixolydian","Aeolian (Minor)","Locrian"]', 'Locrian', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (497, 'scale', 'Dorian ♭2 Scale', 'What scale type is this?', 'jazz', '{"type":"dorian_b2","topic":"melodic_minor_modes"}', '["Melodic Minor","Dorian ♭2","Lydian Augmented","Lydian Dominant","Mixolydian ♭6","Locrian ♯2","Altered"]', 'Dorian ♭2', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (498, 'scale', 'Lydian Augmented Scale', 'What scale type is this?', 'jazz', '{"type":"lydian_aug","topic":"melodic_minor_modes"}', '["Melodic Minor","Dorian ♭2","Lydian Augmented","Lydian Dominant","Mixolydian ♭6","Locrian ♯2","Altered"]', 'Lydian Augmented', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (499, 'scale', 'Mixolydian ♭6 Scale', 'What scale type is this?', 'jazz', '{"type":"mixolydian_b6","topic":"melodic_minor_modes"}', '["Melodic Minor","Dorian ♭2","Lydian Augmented","Lydian Dominant","Mixolydian ♭6","Locrian ♯2","Altered"]', 'Mixolydian ♭6', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (500, 'scale', 'Locrian ♯2 Scale', 'What scale type is this?', 'jazz', '{"type":"locrian_s2","topic":"melodic_minor_modes"}', '["Melodic Minor","Dorian ♭2","Lydian Augmented","Lydian Dominant","Mixolydian ♭6","Locrian ♯2","Altered"]', 'Locrian ♯2', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (501, 'scale', 'Whole Tone Scale', 'What scale type is this?', 'jazz', '{"type":"whole_tone","topic":"jazz_symmetric"}', '["Whole Tone","Half-Whole Diminished","Whole-Half Diminished","Melodic Minor","Lydian Dominant","Altered"]', 'Whole Tone', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (502, 'scale', 'Half-Whole Diminished Scale', 'What scale type is this?', 'jazz', '{"type":"half_whole","topic":"jazz_symmetric"}', '["Whole Tone","Half-Whole Diminished","Whole-Half Diminished","Melodic Minor","Lydian Dominant","Altered"]', 'Half-Whole Diminished', 1782855328, 1782855328, NULL);
INSERT INTO public.exercises VALUES (503, 'scale', 'Whole-Half Diminished Scale', 'What scale type is this?', 'jazz', '{"type":"whole_half","topic":"jazz_symmetric"}', '["Whole Tone","Half-Whole Diminished","Whole-Half Diminished","Melodic Minor","Lydian Dominant","Altered"]', 'Whole-Half Diminished', 1782855328, 1782855328, NULL);

-- Reset sequences to avoid conflicts with future inserts
SELECT pg_catalog.setval('public.exercises_id_seq', 508, true);
SELECT pg_catalog.setval('public.admin_users_id_seq', 1, false);
